
// Objective-C API for talking to the following Go packages
//
//	github.com/celer-network/goCeler/celersdk
//	github.com/ethereum/go-ethereum/mobile
//	github.com/celer-network/appservice/appsdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Celersdk_FRAMEWORK_H__
#define __Celersdk_FRAMEWORK_H__

#include "Celersdk.objc.h"
#include "Geth.objc.h"
#include "Appsdk.objc.h"
#include "universe.objc.h"

#endif
