// Objective-C API for talking to github.com/celer-network/goCeler/celersdk Go package.
//   gobind -lang=objc github.com/celer-network/goCeler/celersdk
//
// File is generated by gobind. Do not edit.

#ifndef __Celersdk_H__
#define __Celersdk_H__

@import Foundation;
#include "Universe.objc.h"


@class CelersdkBalance;
@class CelersdkBooleanCondition;
@class CelersdkCApp;
@class CelersdkClient;
@protocol CelersdkCAppCallback;
@class CelersdkCAppCallback;

@protocol CelersdkCAppCallback <NSObject>
- (BOOL)onReceiveState:(NSData*)state;
- (void)onStatusChanged:(long)status;
@end

/**
 * offchain balance struct
 */
@interface CelersdkBalance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)available;
- (void)setAvailable:(NSString*)v;
- (NSString*)pending;
- (void)setPending:(NSString*)v;
- (NSString*)total;
- (void)setTotal:(NSString*)v;
@end

@interface CelersdkBooleanCondition : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (int64_t)timeout;
- (void)setTimeout:(int64_t)v;
- (NSString*)sessionID;
- (void)setSessionID:(NSString*)v;
- (NSData*)argsForIsFinal;
- (void)setArgsForIsFinal:(NSData*)v;
- (NSData*)argsForQueryResult;
- (void)setArgsForQueryResult:(NSData*)v;
@end

@interface CelersdkCApp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)contractBin;
- (void)setContractBin:(NSString*)v;
- (NSString*)contractAbi;
- (void)setContractAbi:(NSString*)v;
- (id<CelersdkCAppCallback>)callback;
- (void)setCallback:(id<CelersdkCAppCallback>)v;
@end

@interface CelersdkClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewClient creates a new Celer Client based on provided config
@param keyStore the keystore json file content
@param pass	passphrase for keystore
@param cfg json format Celer config
@return a Celer client or null if error
@throws Exception
 */
- (instancetype)init:(NSString*)keyStore pass:(NSString*)pass cfg:(NSString*)cfg;
- (BOOL)endCAppSession:(NSString*)sessionid winnerIdx:(long)winnerIdx error:(NSError**)error;
/**
 * Get celer offchain balance
option = 1: return balance based on only local knowledge
option = 2: return balance based on local knowledge + on-chain knowledge
 */
- (CelersdkBalance*)getBalance:(long)option;
/**
 * HasJoinedCeler Check whether address has also joined Celer and
returns its free balance as a decimal string.  It is useful for
checking the state of the intended receiver.
If the given address has not joined Celer, an empty string will
be returned.
 */
- (NSString*)hasJoinedCeler:(NSString*)addr error:(NSError**)error;
/**
 * JoinCeler network by opening a channel with cNode, blocks until onchain tx completes
return channel id as string or error msg
 */
- (NSString*)joinCeler:(NSString*)tokenaddr amtWei:(NSString*)amtWei peerAmtWei:(NSString*)peerAmtWei error:(NSError**)error;
/**
 * LeaveCeler network by settling all off-chain balance, blocks until onchain tx completes
 */
- (void)leaveCeler;
/**
 * NewCAppSession creates a new CApp session and return the session identifier as string
 */
- (NSString*)newCAppSession:(CelersdkCApp*)capp constructor:(NSString*)constructor nonce:(int64_t)nonce error:(NSError**)error;
/**
 * NewOnChainOracle creates a new on-chain oracle that the conditional payment could depend on
 */
- (BOOL)newOnChainOracle:(NSString*)oracleAddr abi:(NSString*)abi error:(NSError**)error;
/**
 * ResolvePaymentByOracle resolves a conditional payment if the condition has been settled by the
corresponding on-chain oracle
 */
- (BOOL)resolvePaymentByOracle:(NSString*)oracleAddr error:(NSError**)error;
- (BOOL)sendCAppState:(NSString*)sessionid dst:(NSString*)dst state:(NSData*)state error:(NSError**)error;
/**
 * SendPay amtWei to dst using Celer off-chain payment
 */
- (BOOL)sendPay:(NSString*)dst amtWei:(NSString*)amtWei error:(NSError**)error;
- (BOOL)sendPayWithConditions:(NSString*)dst amtWei:(NSString*)amtWei cond:(CelersdkBooleanCondition*)cond error:(NSError**)error;
- (NSString*)switchToOnchain:(NSString*)sessionid error:(NSError**)error;
@end

/**
 * NewClient creates a new Celer Client based on provided config
@param keyStore the keystore json file content
@param pass	passphrase for keystore
@param cfg json format Celer config
@return a Celer client or null if error
@throws Exception
 */
FOUNDATION_EXPORT CelersdkClient* CelersdkNewClient(NSString* keyStore, NSString* pass, NSString* cfg, NSError** error);

FOUNDATION_EXPORT void CelersdkOnLog(long num);

@class CelersdkCAppCallback;

@interface CelersdkCAppCallback : NSObject <goSeqRefInterface, CelersdkCAppCallback> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (BOOL)onReceiveState:(NSData*)state;
- (void)onStatusChanged:(long)status;
@end

#endif
